### PR TITLE
HipChat Enterprise Server and Assembly Version fix

### PR DESCRIPTION
**Pull request by xremix**
This allows the User to specify a In-House Enterprise Server and I also fixed the Assembly Version as it was on 1.2.0 and the current version is 1.3.0, so I set it to 1.3.1 with this feature.

### CODE REVIEW

**Comment by xremix** [comment]
@uygary not sure if you get notifications for pull requests, so here is a little notification.

**Comment by xremix** [comment]
awesome thanks @uygary for the fast merge, maybe you can push it to nuget sometime.

**Comment by uygary** [comment]
No, thank you for the pull request.
Actually I have a huge refactor of the codebase which I've been testing, but it's not ready for merge yet. But there are a couple of tiny changes in it which I'd like to get out as well.
So I'll reflect those changes over as well, in a few days, and release the package.

**Comment by xremix** [comment]
@uygary sounds good to me and looking forward to that. It seems I can only include the library in .NET Core 5 using Nuget, wich stops me using my own feature on a .NET Core project. I test around and wanted to get this running cross-platform.

**Comment by xremix** [comment]
@uygary this is still not out in Nuget, is it?

**Comment by uygary** [comment]
My changes aren't, but this fix is.

**Comment by xremix** [comment]
Ah perfect thank you sir.

**Pull request merged**
